theme: just-the-docs
base:
  url: lucianofedericopereira.github.io
  folder: articles
meta:
  title: design﹢code
  tagline: CodeCraft Chronicles
  author: Luciano Pereira  
  repository: https://github.com/lucianofedericopereira
  license: GPLv2
  locale: en
fonts:
  text: Mediaan-Regular
  titles: VisueltPro-Regular
  code: JetBrainsMono-Medium
links:
  LinkedIn: https://github.com/just-the-docs/just-the-docs
  GitHub: https://github.com/just-the-docs/just-the-docs-template      

collections_dir: _posts
collections:
  css:
    permalink: ":collection/:path/"
    output: true
  js:
    permalink: ":collection/:path/"
    output: true
defaults:
  - scope:
      path: "index.md"
    values:
      layout: codecraft
      comments: false
      mermaid: false
  - scope:
      path: "category"
    values:
      layout: codecraft
      comments: false
      mermaid: false
  - scope:
      path: "_css"
    values:
      layout: codecraft
      comments: false
      mermaid: false
  - scope:
      path: "_js"
    values:
      layout: codecraft
      comments: false
      mermaid: false
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
utteranc:
  theme: github-light
  issue: title
  repo: lucianofedericopereira/comments
  src: https://utteranc.es/client.js
version:
  mermaid: 11.4.1
  lunr: 2.3.9
#gh_edit_branch: "main" # the branch that your docs is served from
## gh_edit_source: docs # the source that your files originate from

