theme: just-the-docs
search_enabled: false
base:
  url: lucianofedericopereira.github.io
  folder: articles
meta:
  title: design﹢code
  tagline: CodeCraft Chronicles
  author: Luciano Pereira  
  repository: https://github.com/lucianofedericopereira
  license: GPLv2
  locale: en
fonts:
  - type: title
    name: Mediaan
    weight: Regular
    extension: woff2
  - type: body
    name: VisueltPro
    weight: Regular
    extension: woff2
  - type: code
    name: JetBrainsMono
    weight: Medium
    extension: woff2
colors:
  ca: FF7E4B
  c0: 111017
  ce: 4D7A77
  c1: 453E35
  c2: 554E45
  cd: A5A983
  c3: C2C5A5
  c4: DFDDCA
  cb: DFF6C3
  c5: E3F0DF
  cc: E3E7D9
  c6: F1F6E5
  c7: FFFFF8
  c8: FF9B67
  c9: FFDEA3
  r0: 005F9E
  r1: 2F6F91
  r2: 333333
  r3: 407A52
  r4: 4287F5
  r5: 4A4A4A
  r6: 6B7FBB
  r7: 888888
  r8: 9366A5
  r9: A41834
  ra: A8C079
  rb: C44D5E
  rc: C64040
  rd: D4E6A5
  re: DFF3C6
  rf: F6FAEB



links:
  LinkedIn: https://github.com/just-the-docs/just-the-docs
  GitHub: https://github.com/just-the-docs/just-the-docs-template      

collections:
  css:
    permalink: "/:collection/:path/"
    output: true
  js:
    permalink: "/:collection/:path/"
    output: true

defaults:
  - scope:
      path: "index.md"
    values:
      layout: codecraft
      comments: false
      mermaid: false
  - scope:
      path: "category"
    values:
      layout: codecraft
      comments: false
      mermaid: false
  - scope:
      path: "_css"
    values:
      layout: codecraft
      comments: false
      mermaid: false
  - scope:
      path: "_js"
    values:
      layout: codecraft
      comments: false
      mermaid: false
utteranc:
  theme: github-light
  issue: title
  repo: lucianofedericopereira/comments
  src: https://utteranc.es/client.js
version:
  mermaid: 11.4.1
  lunr: 2.3.9
#gh_edit_branch: "main" # the branch that your docs is served from
## gh_edit_source: docs # the source that your files originate from

