theme: just-the-docs
base:
  url: lucianofedericopereira.github.io
  folder: articles
meta:
  title: design﹢code
  author: Luciano Pereira
  repository: https://github.com/lucianofedericopereira
  copyright: "design﹢code ©{{ site.time | date: '%Y' }} Luciano Pereira"
  license: GPLv2
  locale: en
fonts:
  text: Mediaan-Regular
  titles: VisueltPro-Regular
  code: JetBrainsMono-Medium
links:
  LinkedIn: https://github.com/just-the-docs/just-the-docs
  GitHub: https://github.com/just-the-docs/just-the-docs-template      
collections:
  css:
    permalink: "/:collection/:path/"
    output: true
  js:
    permalink: "/:collection/:path/"
    output: true
defaults:
  - scope:
      path: "index.md"
    values:
      layout: codecraft
      comments: false
      mermaid: false
  - scope:
      path: "category"
    values:
      layout: codecraft
      comments: false
      mermaid: false
  - scope:
      path: "_css"
    values:
      layout: codecraft
      comments: false
      mermaid: false
  - scope:
      path: "_js"
    values:
      layout: codecraft
      comments: false
      mermaid: false
search:
  heading_level: 1
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: false
  button: false
  focus_shortcut_key: 'k'
version:
  mermaid: 11.4.1

#gh_edit_branch: "main" # the branch that your docs is served from
## gh_edit_source: docs # the source that your files originate from

