theme: just-the-docs
permalink: pretty
post_limit: 10
sidebar_collections: false
search_enabled: false
search_file: https://lucianofedericopereira.github.io/articles/search.json
base:
  url: lucianofedericopereira.github.io
  folder: articles
meta:
  title: design﹢code
  tagline: CodeCraft Chronicles
  author: Luciano Pereira  
  repository: https://github.com/lucianofedericopereira
  license: GPLv2
  locale: en
links:
  LinkedIn: https://github.com/just-the-docs/just-the-docs
  GitHub: https://github.com/just-the-docs/just-the-docs-template      
fonts:
  - type: title
    name: Mediaan
    weight: Regular
    extension: woff2
  - type: body
    name: VisueltPro
    weight: Regular
    extension: woff2
  - type: code
    name: JetBrainsMono
    weight: Medium
    extension: woff2
collections:
  design:
    permalink: "/:collection/:name/"
    output: true
  code:
    permalink: "/:collection/:name/"
    output: true
  projects:
    permalink: "/:collection/:name/"
    output: true
defaults:
  - scope:
      path: "index.md"
    values:
      layout: codeCraft
      toc: false
      comments: false
      mermaid: false
      codepen: false
  - scope:
      path: "category"
    values:
      layout: codeCraft
      banner: true
      toc: false
      comments: false
      mermaid: false
      codepen: false
  - scope:
      path: "_design"
    values:
      layout: codeCraft
      toc: true
      comments: false
      mermaid: false
      codepen: false
  - scope:
      path: "_code"
    values:
      layout: codeCraft
      toc: true
      comments: false
      mermaid: false
      codepen: false
  - scope:
      path: "_project"
    values:
      layout: codeCraft
      toc: true
      comments: false
      mermaid: false
      codepen: false
utteranc:
  theme: github-light
  issue: title
  repo: lucianofedericopereira/comments
  src: https://utteranc.es/client.js
version:
  mermaid: 11.4.1
  lunr: 2.3.9
#gh_edit_branch: "main" # the branch that your docs is served from
## gh_edit_source: docs # the source that your files originate from