meta:
  domain: https://lucianofedericopereira.github.io
  author: Luciano Pereira

  url: {meta.domain}/articles
  assets: {meta.url}/assets
  images: {meta.assets}/images
  icon: {meta.images}/favicon.ico

links:
  LinkedIn: https://github.com/just-the-docs/just-the-docs
  GitHub: https://github.com/just-the-docs/just-the-docs-template      


title: design﹢code
description: "CodeCraft Chronicles"
author: Luciano Pereira

copyright: "design﹢code (c) {currentYear} {meta.author}"
footer_content: "Copyright &copy; {currentYear} Luciano Perera"

#gh_edit_branch: "main" # the branch that your docs is served from
## gh_edit_source: docs # the source that your files originate from

collections:
  css:
    permalink: "/:collection/:path/"
    output: true
  js:
    permalink: "/:collection/:path/"
    output: true
defaults:
  - scope:
      path: "_css"
    values:
      layout: codecraft
      comments: false
  - scope:
      path: "_js"
    values:
      layout: codecraft
      comments: false
favicon_ico: "/assets/images/favicon.ico"
logo: "/assets/images/favicon.ico"
mermaid:
  version: "11.4.1"
search:
  heading_level: 1 # 1-6
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: false
  button: false
  focus_shortcut_key: 'k'
theme: just-the-docs
url: https://lucianofedericopereira.github.io/articles