title: design﹢code
author: Luciano Pereira
email: lucianofullstack@duck.com
description: "CodeCraft Chronicles"
copyright: "design﹢code (c) {currentYear} {author}"
footer_content: "Copyright &copy; {currentYear} Luciano Perera"
aux_links_new_tab: false
search_enabled: true

#last_edit_timestamp: true
#last_edit_time_format: "%b %e %Y at %I:%M %p" # https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
#gh_edit_branch: "main" # the branch that your docs is served from
## gh_edit_source: docs # the source that your files originate from

collections:
  css:
    permalink: "/:collection/:path/"
    output: true
  js:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    css:
      name: CSS3
    js:
      name: JavaScript
defaults:
  - scope:
      type: "posts"
    values:
      comments: false
      layout: codecraft
aux_links:
  "LinkedIn":
    - "//github.com/just-the-docs/just-the-docs"
  GitHub: https://github.com/just-the-docs/just-the-docs-template
favicon_ico: "/assets/images/favicon.ico"
logo: "/assets/images/favicon.ico"
mermaid:
  version: "11.4.1"
search:
  heading_level: 1
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: false
  button: false
  focus_shortcut_key: 'k'
theme: just-the-docs
url: https://lucianofedericopereira.github.io/articles
