name: Generate and Deploy Search Index

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual runs

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Setup Ruby Environment
      - name: Setup Ruby Environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      # Step 3: Install Dependencies
      - name: Install Jekyll Dependencies
        run: |
          gem install bundler
          bundle install

      # Step 4: Build the Jekyll Site
      - name: Build Jekyll Site
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      # Step 5: Generate Search Index
      - name: Generate Search Index
        run: ruby scripts/generate_search_data.rb

      # Step 6: Verify Search Index File
      - name: Verify Search JSON
        run: |
          if [ ! -f "assets/json/search.json" ]; then
            echo "Error: search.json file not found!"
            exit 1
          fi
          echo "search.json file exists and is ready."

      # Step 7: Upload Built Site and Search Index
      - name: Upload Site and Search Index
        uses: actions/upload-pages-artifact@v1
        with:
          path: _site # Upload the entire built site, including generated assets

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Step 8: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
